"""
FortyGuard Heat Intelligence Reports Dataset.
Synthesized empirical records from all 9 Indianapolis FortyGuard Heat Intelligence Reports.
"""

FORTYGUARD_REPORTS_DATA = [
    {
        "id": "FG-IND-001",
        "name": "Downtown Commercial Core (E Market St)",
        "location": {"lat": 39.7580, "lng": -86.1340},
        "land_cover": "High-Density Commercial & Mixed-Use",
        "canopy_cover_pct": 14.0,
        "sky_view_factor": 0.45,
        "dominant_materials": ["Asphalt (Albedo 0.08)", "Concrete (Albedo 0.28)", "Glass Facades", "Brick"],
        "baseline_temp_c": 21.47,
        "peak_daytime_temp_c": 37.8,
        "peak_surface_temp_c": 62.5,
        "uhi_intensity_c": 4.8,
        "traffic_heat_flux_wm2": 32.0,
        "hvac_exhaust_load_mw": 65.0,
        "anthropogenic_heat_wm2": 45.0,
        "key_risk_factors": ["Deep street canyon longwave radiation trapping", "Extensive dark asphalt street network", "Concentrated commercial HVAC rejection"],
        "recommended_interventions": ["High-albedo cool pavement coating (Albedo > 0.40)", "Deciduous street tree canopy expansion (+25%)", "Cool roof retrofits on mid-rise buildings"]
    },
    {
        "id": "FG-IND-002",
        "name": "Central Canal & Towpath Promenade",
        "location": {"lat": 39.7436, "lng": -86.1400},
        "land_cover": "Riparian / Waterway Green Corridor",
        "canopy_cover_pct": 42.0,
        "sky_view_factor": 0.78,
        "dominant_materials": ["Open Water Canal", "Turfgrass (Albedo 0.24)", "Stone Pavers", "Mature Hardwood Trees"],
        "baseline_temp_c": 21.43,
        "peak_daytime_temp_c": 33.2,
        "peak_surface_temp_c": 36.4,
        "uhi_intensity_c": -3.2,
        "traffic_heat_flux_wm2": 0.0,
        "hvac_exhaust_load_mw": 2.0,
        "anthropogenic_heat_wm2": 5.0,
        "key_risk_factors": ["High pedestrian exposure during midday if leaving shaded riparian bank", "Microclimate humidity elevation (mean 79%)"],
        "recommended_interventions": ["Maintain dense riparian buffer canopy", "Expand shaded pedestrian wayfinding to channel commuters along cool canal towpath"]
    },
    {
        "id": "FG-IND-003",
        "name": "West Logistics & Freight Hub",
        "location": {"lat": 39.7240, "lng": -86.1822},
        "land_cover": "Heavy Industrial & Transportation Logistics",
        "canopy_cover_pct": 5.0,
        "sky_view_factor": 0.92,
        "dominant_materials": ["Dark Asphalt Parking Pads (Albedo 0.05)", "Corrugated Metal Roofing (Albedo 0.15)", "Paved Loading Docks"],
        "baseline_temp_c": 20.90,
        "peak_daytime_temp_c": 39.2,
        "peak_surface_temp_c": 68.0,
        "uhi_intensity_c": 5.9,
        "traffic_heat_flux_wm2": 55.0,
        "hvac_exhaust_load_mw": 85.0,
        "anthropogenic_heat_wm2": 70.0,
        "key_risk_factors": ["Expansive unshaded asphalt surfaces (surface temp > 65°C)", "Continuous diesel truck idling and exhaust heat", "Zero tree canopy shading"],
        "recommended_interventions": ["Permeable high-albedo paving in loading zones", "Perimeter evergreen/deciduous windbreak buffers", "Reflective cool roof mandates for logistics warehouses"]
    },
    {
        "id": "FG-IND-004",
        "name": "West Washington Residential Corridor",
        "location": {"lat": 39.7539, "lng": -86.2016},
        "land_cover": "Mid-Density Residential & Neighborhood Commercial",
        "canopy_cover_pct": 21.0,
        "sky_view_factor": 0.72,
        "dominant_materials": ["Asphalt Shingles (Albedo 0.10)", "Concrete Sidewalks (Albedo 0.30)", "Residential Lawns"],
        "baseline_temp_c": 21.12,
        "peak_daytime_temp_c": 36.4,
        "peak_surface_temp_c": 54.0,
        "uhi_intensity_c": 2.4,
        "traffic_heat_flux_wm2": 18.0,
        "hvac_exhaust_load_mw": 25.0,
        "anthropogenic_heat_wm2": 22.0,
        "key_risk_factors": ["Unshaded pedestrian sidewalks on wide residential streets", "Older housing stock with high window AC waste heat emissions"],
        "recommended_interventions": ["Residential street tree planting program targeting 35% canopy", "Cool pavement coating on neighborhood bus stops"]
    },
    {
        "id": "FG-IND-005",
        "name": "North Meridian Commercial & Highway Strip",
        "location": {"lat": 39.7941, "lng": -86.1463},
        "land_cover": "Commercial Strip & Interstate 65 Interchange",
        "canopy_cover_pct": 11.0,
        "sky_view_factor": 0.65,
        "dominant_materials": ["Arterial Asphalt (Albedo 0.06)", "Commercial Flat Roofs", "Concrete Strip Malls"],
        "baseline_temp_c": 21.47,
        "peak_daytime_temp_c": 38.5,
        "peak_surface_temp_c": 64.0,
        "uhi_intensity_c": 4.5,
        "traffic_heat_flux_wm2": 48.0,
        "hvac_exhaust_load_mw": 52.0,
        "anthropogenic_heat_wm2": 58.0,
        "key_risk_factors": ["High vehicle volume (150,000+ veh/day) generating 15-25 W/m² waste heat", "Extensive commercial parking lots with low albedo"],
        "recommended_interventions": ["Solar canopy shading over retail parking structures", "Median strip bioswales and shade trees", "Transit stop shade shelters"]
    },
    {
        "id": "FG-IND-006",
        "name": "Monument Circle Civic Center",
        "location": {"lat": 39.7684, "lng": -86.1580},
        "land_cover": "Civic High-Rise & Pedestrian Plaza",
        "canopy_cover_pct": 18.0,
        "sky_view_factor": 0.35,
        "dominant_materials": ["Brick Masonry (Albedo 0.30)", "Limestone Monument", "Reflective Glass Curtain Walls"],
        "baseline_temp_c": 21.50,
        "peak_daytime_temp_c": 38.9,
        "peak_surface_temp_c": 59.5,
        "uhi_intensity_c": 5.2,
        "traffic_heat_flux_wm2": 28.0,
        "hvac_exhaust_load_mw": 90.0,
        "anthropogenic_heat_wm2": 62.0,
        "key_risk_factors": ["Extreme thermal lag retaining heat past midnight (DTR < 13°F)", "Reflected solar glare from high-rise glass curtain walls (MRT +8°C)", "Low Sky View Factor (0.35) preventing nocturnal radiative cooling"],
        "recommended_interventions": ["Deploy mobile solar misting pavilions", "Add green wall vertical facades on civic structures", "Cool pavement resurfacing of pedestrian plaza"]
    },
    {
        "id": "FG-IND-007",
        "name": "Military Park & University Green Zone",
        "location": {"lat": 39.7712, "lng": -86.1685},
        "land_cover": "Urban Regional Park & Pervious Lawns",
        "canopy_cover_pct": 46.0,
        "sky_view_factor": 0.88,
        "dominant_materials": ["Mature Oak & Maple Canopy (Albedo 0.22)", "Pervious Topsoil", "Paved Pedestrian Trails"],
        "baseline_temp_c": 20.80,
        "peak_daytime_temp_c": 31.8,
        "peak_surface_temp_c": 32.5,
        "uhi_intensity_c": -4.6,
        "traffic_heat_flux_wm2": 2.0,
        "hvac_exhaust_load_mw": 0.5,
        "anthropogenic_heat_wm2": 3.0,
        "key_risk_factors": ["Perimeter roads exposed to high heat while park interior remains cool oasis"],
        "recommended_interventions": ["Designate as primary municipal heat refuge zone", "Connect park cool corridors directly with university campus walking paths"]
    },
    {
        "id": "FG-IND-008",
        "name": "Julia M. Carson Transit Center Hub",
        "location": {"lat": 39.7645, "lng": -86.1485},
        "land_cover": "Central Public Transit Hub & Bus Bays",
        "canopy_cover_pct": 8.0,
        "sky_view_factor": 0.70,
        "dominant_materials": ["Dark Asphalt Bus Bays", "Precast Concrete Platforms", "Steel Shelters"],
        "baseline_temp_c": 21.60,
        "peak_daytime_temp_c": 39.6,
        "peak_surface_temp_c": 66.5,
        "uhi_intensity_c": 5.8,
        "traffic_heat_flux_wm2": 62.0,
        "hvac_exhaust_load_mw": 40.0,
        "anthropogenic_heat_wm2": 68.0,
        "key_risk_factors": ["High commuter dwell time (20-30 min waiting in peak heat)", "Heavy diesel bus exhaust and engine heat accumulation", "Very low tree canopy (8%) and high radiant surface heat"],
        "recommended_interventions": ["High-urgency cantilevered shade structures with photovoltaic cooling", "Active high-pressure misting lines at boarding platforms", "High-albedo reflective bus bay surfacing"]
    },
    {
        "id": "FG-IND-009",
        "name": "South Meridian Light Industrial & Tech Corridor",
        "location": {"lat": 39.7490, "lng": -86.1620},
        "land_cover": "Light Industrial, Data Centers & Rail Corridor",
        "canopy_cover_pct": 12.0,
        "sky_view_factor": 0.68,
        "dominant_materials": ["Aged Asphalt (Albedo 0.08)", "Concrete Masonry", "Steel Rail Bedding"],
        "baseline_temp_c": 21.20,
        "peak_daytime_temp_c": 37.5,
        "peak_surface_temp_c": 60.0,
        "uhi_intensity_c": 3.9,
        "traffic_heat_flux_wm2": 35.0,
        "hvac_exhaust_load_mw": 48.0,
        "anthropogenic_heat_wm2": 42.0,
        "key_risk_factors": ["Data center continuous HVAC heat rejection", "Unshaded rail corridor absorbing solar radiation"],
        "recommended_interventions": ["Waste heat recovery integration", "Tree canopy green buffers along rail and arterial boundaries"]
    }
]
